# Generated by Django 4.1.1 on 2022-11-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaplus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotas',
            old_name='mas',
            new_name='idmascota',
        ),
    ]
